# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
        
    strategy:
      matrix:
        DJANGO_VERSION: ['4.1.*', '4.2.*', '5.0.*', '5.1.*', '5.2.*']
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
        exclude:
          # Django 4.1
          - DJANGO_VERSION: '4.1.*'
            python-version: '3.12'
          - DJANGO_VERSION: '4.1.*'
            python-version: '3.13'
          # Django 4.2
          - DJANGO_VERSION: '4.2.*'
            python-version: '3.13'
          # Django 5.0
          - DJANGO_VERSION: '5.0.*'
            python-version: '3.9'
          - DJANGO_VERSION: '5.0.*'
            python-version: '3.13'
          # Django 5.1
          - DJANGO_VERSION: '5.1.*'
            python-version: '3.9'
          # Django 5.2
          - DJANGO_VERSION: '5.2.*'
            python-version: '3.9'
      fail-fast: false

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
              python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('setup.py') }}-${{ matrix.DJANGO_VERSION }}

      - name: Install
        run: |
           pip install setuptools
           python setup.py develop
           pip install -e .
           pip install -r requirements_test.txt
           pip install coveralls
           pip install psycopg2
           pip install Django==${{ matrix.DJANGO_VERSION }}
           pip install codecov

      - name: Testing
        run: |
          PYTHONPATH=`pwd` python -W error::DeprecationWarning -m coverage run --source social_2fa runtests.py social_2fa
          coverage xml && codecov
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost/postgres"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('setup.py') }}-${{ matrix.DJANGO_VERSION }}

      - name: Install
        run: |
          pip install flake8 isort black mypy django-stubs dj_database_url types-six types-requests types-mock setuptools
          python setup.py develop
          pip install -e .
          pip install -r requirements.txt
      - name: Running Flake8
        run: flake8
      - name: Running isort
        run: python -m isort social_2fa tests --check-only --diff
      - name: Running black
        run: black --check social_2fa tests
      - name: Running mypy
        run: mypy social_2fa tests --ignore-missing-imports
